server:
  port: ${PORT:8080}

spring:
  application:
    name: api
  data:
    mongodb:
      uri: ${DB_CONNECTION_STRING}
      database: tfg
      port: 27017

sendgrid:
  api-key: ${MAIL_PASSWORD}
  from: ${FROM}

jwt:
  secret: ${JWT_SECRET}
