server:
  port: 8080
spring:
  application:
    name: api
  data:
    mongodb:
      uri: ${DB_CONNECTION_STRING}
      database: tfg
      port: 27017
  mail:
    host: smtp.gmail.com
    port: 587
    username: sistemadegestionagropecuaria@gmail.com
    password: iwncmhpeebececyc
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
jwt:
  secret: 7Gq86w8cs6y3ptA42UE0iPtbJwsaeUW5EYXPXD1vxi4R7rQyiarcb78XRt7AG9mY